<a href="https://colab.research.google.com/github/BimalGhimire38/Extra_Python_Stuffs/blob/main/Revision_PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2082/11/12  08:38 AM

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.values

array([[842302, 'M', 17.99, ..., 0.4601, 0.1189, nan],
       [842517, 'M', 20.57, ..., 0.275, 0.08902, nan],
       [84300903, 'M', 19.69, ..., 0.3613, 0.08758, nan],
       ...,
       [926954, 'M', 16.6, ..., 0.2218, 0.0782, nan],
       [927241, 'M', 20.6, ..., 0.4087, 0.124, nan],
       [92751, 'B', 7.76, ..., 0.2871, 0.07039, nan]], dtype=object)

In [4]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [5]:
df.shape

(569, 33)

In [6]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train Test Split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

# Scaling

In [9]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [10]:
x_train

array([[ 0.22261223,  0.93853413,  0.36341344, ...,  0.89309162,
         0.17450328,  0.18341388],
       [ 0.11969297, -1.97464006,  0.10929808, ...,  0.11894276,
        -0.01109824, -0.20891577],
       [-0.48066941, -0.36908383, -0.42260026, ..., -0.62154745,
        -0.56790279,  0.5548569 ],
       ...,
       [ 0.61713608, -0.11134358,  0.71219924, ...,  0.90074131,
        -0.21007644,  1.27234032],
       [-0.54070564, -1.40713859, -0.52183812, ..., -0.49655148,
         0.95871148,  0.48824554],
       [ 0.99736558, -0.99097085,  0.96963637, ...,  0.4784783 ,
        -0.23348564, -0.25802754]])

In [11]:
y_train

194    M
123    B
431    B
85     M
169    B
      ..
35     M
369    M
283    M
130    B
29     M
Name: diagnosis, Length: 455, dtype: object

# Label Encoding

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1])

In [14]:
x_train

array([[ 0.22261223,  0.93853413,  0.36341344, ...,  0.89309162,
         0.17450328,  0.18341388],
       [ 0.11969297, -1.97464006,  0.10929808, ...,  0.11894276,
        -0.01109824, -0.20891577],
       [-0.48066941, -0.36908383, -0.42260026, ..., -0.62154745,
        -0.56790279,  0.5548569 ],
       ...,
       [ 0.61713608, -0.11134358,  0.71219924, ...,  0.90074131,
        -0.21007644,  1.27234032],
       [-0.54070564, -1.40713859, -0.52183812, ..., -0.49655148,
         0.95871148,  0.48824554],
       [ 0.99736558, -0.99097085,  0.96963637, ...,  0.4784783 ,
        -0.23348564, -0.25802754]])

In [15]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
x_train_tensor

tensor([[ 0.2226,  0.9385,  0.3634,  ...,  0.8931,  0.1745,  0.1834],
        [ 0.1197, -1.9746,  0.1093,  ...,  0.1189, -0.0111, -0.2089],
        [-0.4807, -0.3691, -0.4226,  ..., -0.6215, -0.5679,  0.5549],
        ...,
        [ 0.6171, -0.1113,  0.7122,  ...,  0.9007, -0.2101,  1.2723],
        [-0.5407, -1.4071, -0.5218,  ..., -0.4966,  0.9587,  0.4882],
        [ 0.9974, -0.9910,  0.9696,  ...,  0.4785, -0.2335, -0.2580]],
       dtype=torch.float64)

In [17]:
x_train_tensor.shape

torch.Size([455, 30])

In [18]:
x_test_tensor.shape

torch.Size([114, 30])

# Defining the Model

In [19]:
class MySimpleNN():

  def __init__(self,x):

    self.weights = torch.rand(x.shape[1],1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def forward(self, x):
    z = torch.matmul(x, self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred)).mean()
    return loss

# Importand Parameters

In [20]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [21]:
# create models
model = MySimpleNN(x_train_tensor)
# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)
  # print(y_pred)

  # loss calculation
  loss = model.loss_function(y_pred,y_train_tensor)
  # print(f"Epoch: {epoch+1}, Loss: {loss.item()}")
  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate*model.weights.grad
    model.bias -= learning_rate*model.bias.grad

  # print(f"Updated Weights {model.weights}")
  # print(f"Updated Bias {model.bias}")
  # Zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # Print loss in each epoch
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 2.712988371521943
Epoch: 2, Loss: 2.5637035092087688
Epoch: 3, Loss: 2.4073109935328714
Epoch: 4, Loss: 2.250226798009073
Epoch: 5, Loss: 2.0931019127534936
Epoch: 6, Loss: 1.9351113984815993
Epoch: 7, Loss: 1.7814262985935674
Epoch: 8, Loss: 1.635232606840862
Epoch: 9, Loss: 1.4961312547226584
Epoch: 10, Loss: 1.3647425382809808
Epoch: 11, Loss: 1.2468875094780187
Epoch: 12, Loss: 1.1440781487533849
Epoch: 13, Loss: 1.0572938751816696
Epoch: 14, Loss: 0.9867146742712873
Epoch: 15, Loss: 0.931535570457893
Epoch: 16, Loss: 0.8899108014673296
Epoch: 17, Loss: 0.8591922293133305
Epoch: 18, Loss: 0.8365319250938356
Epoch: 19, Loss: 0.8194955919727158
Epoch: 20, Loss: 0.8063076836547964
Epoch: 21, Loss: 0.7957778569957267
Epoch: 22, Loss: 0.787130851263446
Epoch: 23, Loss: 0.779859708948098
Epoch: 24, Loss: 0.7736257356801208
Epoch: 25, Loss: 0.768195831213211

In [22]:
model.bias

tensor([-0.2001], dtype=torch.float64, requires_grad=True)

# Evaluation

In [23]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")
# print(y_pred)

Accuracy: 0.5180055499076843